### ISSUE TITLE
Create An Endpoint To GET Showcase Posts

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/website-backend#15]
`GET /showcase/`

Returns an array of showcase posts, for example:
```js
[
    {
        "id": Number,
        "name": String, 
        "description": String,
        "creator": String,
        "contributors": String[], 
        "link": String
        "img": String?
    }
]
```

**Question:** Should `contributors` be an array of user IDs or names?

**Comment by AtrumAmantus** [comment]
Personally I think linking existing accounts will give us more options later, but you'd still want to credit those without one.  Maybe do like discord, string tag that references an id, but if it doesn't exist, it's just a string

**Comment by AtrumAmantus** [comment]
What about original poster? That should probably be a separate property

**Comment by LamboCreeper** [comment]
> Personally I think linking existing accounts will give us more options later, but you'd still want to credit those without one. Maybe do like discord, string tag that references an id, but if it doesn't exist, it's just a string

Valid point, maybe we could do an array of objects with an optional key of their user ID.

> What about original poster? That should probably be a separate property

I didn't include this as this way all contributors are equal (if there is only one contributor the array would have a single index).

**Comment by AtrumAmantus** [comment]
No one else would see the poster ID, it's for the back end to track things

**Comment by LamboCreeper** [comment]
Cool, let's add that in then.
